#! /bin/sh
VAR=$$

XTERM_PARAM="-j -rw -sb -sl 1024 -fg white -bg blue -cr white -sk -geometry 70x30 -fn 6x10"

xterm ${XTERM_PARAM} -e /bin/sh -c "FCFoo -f client.conf $1 $2 2>>/tmp/FCFoo.${VAR} " -e exit &
xterm ${XTERM_PARAM} -e tail -f /tmp/FCFoo.${VAR} &
